config/routes.rb
Blogger::Application.routes.draw do

  root 'articles#index'

  resources :articles do
    resources :comments
  end

  resources :tags
  resources :authors
  resources :author_sessions, only: [:new, :create, :destroy]
  get 'login' => 'author_sessions#new'
  get 'logout' => 'author_sessions#destroy'

end

app/models/article.rb
class Article < ActiveRecord::Base
  has_many :comments
  has_many :taggings
  has_many :tags, through: :taggings
  has_attached_file :image

  def tag_list
    tags.join(", ")
  end

  def tag_list=(tag_string)
    tag_names = tag_string.split(",").collect {|s| s.strip.downcase}.uniq
    self.tags = tag_names.collect {|t| Tag.find_or_create_by(name: t)}
  end
end

app/models/author.rb
class Author < ActiveRecord::Base
  authenticates_with_sorcery!
  validates_confirmation_of :password, message: "should match confirmation", if: :password
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :article
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  has_many :taggings
  has_many :articles, through: :taggings

  def to_s
    name
  end
end

app/models/tagging.rb
class Tagging < ActiveRecord::Base
  belongs_to :tag
  belongs_to :article
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  include ArticlesHelper
  before_filter :require_login, except: [:index, :show]

  def index
    @articles = Article.all
  end

  def show
    @article = Article.find(params[:id])
    @comment = Comment.new
    @comment.article_id = @article.id
  end

  def new
    @article = Article.new
  end

  def create
    fail
    @article = Article.new(article_params)
    @article.save

    flash.notice = "Article '#{@article.title}' Created!"

    redirect_to article_path(@article)
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])
    @article.update(article_params)

    flash.notice = "Article '#{@article.title}' Updated!"

    redirect_to article_path(@article)
  end

  def destroy
    article = Article.find(params[:id])
    article.destroy

    flash.notice = "Article '#{@article.title}' Deleted!"

    redirect_to articles_path
  end
end

app/controllers/author_sessions_controller.rb
class AuthorSessionsController < ApplicationController
  def new
    @author = Author.new
  end

  def create
    if login(params[:author][:email], params[:author][:password])
      redirect_back_or_to(articles_path, notice: 'Logged in successfully.')
    else
      flash.now.alert = "Login failed."
      render action: :new
    end
  end

  def destroy
    logout
    redirect_to(:authors, message: 'Logged out!')
  end
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  before_action :set_author, only: [:show, :edit, :update, :destroy]
  before_filter :zero_authors_or_authenticated, only: [:new, :create]
  before_filter :require_login, except: [:new, :create]

  def zero_authors_or_authenticated
    unless Author.count == 0 || current_user
      redirect_to root_path
      return false
    end
  end

  # GET /authors
  # GET /authors.json
  def index
    @authors = Author.all
  end

  # GET /authors/1
  # GET /authors/1.json
  def show
  end

  # GET /authors/new
  def new
    @author = Author.new
  end

  # GET /authors/1/edit
  def edit
  end

  # POST /authors
  # POST /authors.json
  def create
    @author = Author.new(author_params)

    respond_to do |format|
      if @author.save
        format.html { redirect_to @author, notice: 'Author was successfully created.' }
        format.json { render action: 'show', status: :created, location: @author }
      else
        format.html { render action: 'new' }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /authors/1
  # PATCH/PUT /authors/1.json
  def update
    respond_to do |format|
      if @author.update(author_params)
        format.html { redirect_to @author, notice: 'Author was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /authors/1
  # DELETE /authors/1.json
  def destroy
    @author.destroy
    respond_to do |format|
      format.html { redirect_to authors_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_author
      @author = Author.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def author_params
      params.require(:author).permit(:username, :email, :password, :password_confirmation)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  include CommentsHelper

  before_filter :require_login, except: [:create]

  def create
    @comment = Comment.new(comment_params)
    @comment.article_id = params[:article_id]
    @comment.save

    redirect_to article_path(@comment.article)
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  before_filter :require_login, only: [:destroy]

  def show
    @tag = Tag.find(params[:id])
  end

  def index
    @tags = Tag.all
  end

  def destroy
    tag = Tag.find(params[:id])
    tag.destroy

    flash.notice = "Tag '#{tag.name}' Deleted!"

    redirect_to tags_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
  def article_params
    params.require(:article).permit(:title, :body, :tag_list, :image)
  end
end

app/helpers/author_sessions_helper.rb
module AuthorSessionsHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
  def comment_params
    params.require(:comment).permit(:author_name, :body)
  end
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/articles/_comment.html.haml
.list-group-item
  %h4.list-group-item-heading Comment by #{comment.author_name}
  %p.list-group-item-text= comment.body
  %p.text-muted Posted #{distance_of_time_in_words(comment.article.created_at, comment.created_at)} later

app/views/articles/_form.html.haml
= simple_form_for(@article, html: {multipart: true}) do |f|
  %ul.form-group
    - @article.errors.full_messages.each do |error|
      %li= error
  .form-group
    = f.input :title, label: "Title:", input_html: {class: 'form-control'}
  .form-group
    = f.input :body, as: :text, label: "Description", input_html: {class: 'form-control'}
  .form-group
    = image_tag @article.image.url if @article.image.exists?
    = f.input :image, as: :file, label: "Attach an Image:", input_html: {class: 'form-control'}
  .form-group
    = f.input :tag_list, label: "Tags:", input_html: {class: 'form-control'}
  .form-group
    = f.button :submit, class: 'btn-primary'

app/views/articles/edit.html.haml
%h1 Edit an Article
= render partial: 'form'
%p= link_to "Back to Articles", articles_path

app/views/articles/index.html.haml
%h1 All Articles
%ul#articles
  - @articles.each do |article|
    %li= link_to article.title, article_path(article)
- if logged_in?
  %p= link_to "Create New Article", new_article_path

app/views/articles/new.html.haml
%h1 Create a New Article
= render partial: 'form'
%p= link_to "Back to Articles", articles_path

app/views/articles/show.html.haml
.panel.panel-default
  .panel-heading
    %h3.panel-title= @article.title
  .panel-body
    %p= @article.body
    %p= image_tag @article.image.url if @article.image.exists?
    %p
      Tags:
      - @article.tags.each do |tag|
        = link_to tag.name, tag_path(tag)
%h3 Comments #{@article.comments.size}
.list-group
  = render partial: 'articles/comment', collection: @article.comments
  .div
    = render partial: 'comments/form'
.div
  - if logged_in?
    %p
      = link_to "Edit Article", edit_article_path(@article)
      \|
      = link_to "Delete Article", article_path(@article), method: :delete, data: {confirm: "Really delete the article?"}
  %p= link_to "Back to Articles", articles_path

app/views/author_sessions/create.html.haml
%h1 AuthorSessions#create
%p Find me in app/views/author_sessions/create.html.haml

app/views/author_sessions/destroy.html.haml
%h1 AuthorSessions#destroy
%p Find me in app/views/author_sessions/destroy.html.haml

app/views/author_sessions/new.html.haml
%h1 Login

= simple_form_for [author_sessions_path, @author], url: author_sessions_path, method: :post do |f|
  = f.error_notification

  .form-group
    = f.input :email, input_html: {class: "form-control"}
  .form-group
    = f.input :password, as: :password, input_html: {class: "form-control"}
  .form-group
    = f.button :submit, 'Login', class: 'btn-primary'

%p= link_to 'Back to Articles', articles_path

app/views/authors/_form.html.haml
= simple_form_for(@author) do |f|
  = f.error_notification

  .form-group
    / = f.input :username
    = f.input :email, input_html: {class: 'form-control'}
  .form-group
    = f.input :password, as: :password, input_html: {class: 'form-control'}
  .form-group
    = f.input :password_confirmation, as: :password, input_html: {class: 'form-control'}

  .form-group
    = f.button :submit, class: 'btn-primary'

app/views/authors/edit.html.haml
%h1 Editing author

= render 'form'

= link_to 'Show', @author
\|
= link_to 'Back', authors_path

app/views/authors/index.html.haml
%h1 Listing authors

%table.table
  %tr
    /%th Username
    %th Email
    %th
    %th
    %th

  - @authors.each do |author|
    %tr
      /%td= author.username
      %td= author.email
      %td= link_to 'Show', author
      %td= link_to 'Edit', edit_author_path(author)
      %td= link_to 'Destroy', author, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Author', new_author_path

app/views/authors/new.html.haml
%h1 New author

= render 'form'

= link_to 'Back', authors_path

app/views/authors/show.html.haml
%p#notice= notice

%p
  /%b Username:
  /= @author.username
%p
  %b Email:
  = @author.email

= link_to 'Edit', edit_author_path(@author)
\|
= link_to 'Back', authors_path

app/views/comments/_form.html.haml
%h3 Post a comment
= simple_form_for [@article, @comment] do |f|
  %ul.form-group
    - @article.errors.full_messages.each do |error|
      %li= error
  .form-group
    = f.input :author_name, label: "Your Name:", input_html: {class: 'form-control'}
  .form-group
    = f.input :body, as: :text, label: "Your Comment", input_html: {class: 'form-control'}
  .form-group
    = f.button :submit, class: 'btn-primary'

app/views/layouts/_messages.html.haml
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{:class => "alert alert-#{name == :notice ? "success" : "error"}"}
      %a.close{"data-dismiss" => "alert"} ×
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_navigation.html.haml
.navbar-header
  = link_to "Home", '/', :class => 'navbar-brand'
%ul.nav.navbar-nav
  %li
    = link_to('Home', '/')
  %li
    = link_to('Home', '/')

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:charset => "utf-8"}
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1, maximum-scale=1"}
    %title= content_for?(:title) ? yield(:title) : "Blogger"
    %meta{:content => "", :name => "description"}
    %meta{:content => "", :name => "author"}
    = stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = csrf_meta_tags
    = yield(:head)
  %body
    %header.navbar.navbar-default
      %collapse.navbar-collapse
        .container
          = render 'layouts/navigation'
    #main{:role => "main"}
      .container
        .content
          .row
            .span12
              = render 'layouts/messages'
              = yield
          %footer
          .row
            .span12
              %h6
                - if logged_in?
                  = "Logged in as #{current_user.email}"
                  = link_to '(Logout)', logout_path
                - else
                  = link_to '(Login)', login_path

app/views/tags/index.html.haml
%h1 All Tags
%ul#tags
  - @tags.each do |tag|
    %li
      = link_to tag.name, tag_path(tag)
      - if logged_in?
        = link_to "Delete Tag", tag_path(tag), method: :delete, data: {confirm: "Really delete the tag?"}

app/views/tags/show.html.haml
%h1 Articles Tagged with #{@tag.name}

%ul
  - @tag.articles.each do |article|
    %li= link_to article.title, article_path(article)